language: php

php:
  - 7.2

env:
  - POSTGRES_USER=root
  - POSTGRES_PASSWORD=password
  - CLICKHOUSE_USER=local_user
  - CLICKHOSUE_PASSWORD=password

before_script:
  - chmod +x ./deployment/travis/scripts/install_clickhouse.sh
  - ./deployment/travis/scripts/install_clickhouse.sh
  - cp .env.travis .env
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - php artisan key:generate
  - php artisan migrate

before_install:
  - psql -c 'create database logs_testing;' -U postgres

script:
  - phpunit

services:
  - postgresql
  - rabbitmq

branches:
  only:
    - master
    - develop

notifications:
  email: false
