language: php

php:
  - 7.2

env:
  global:
    - CLICKHOUSE_USER=local_user
    - CLICKHOSUE_PASSWORD=password

before_script:
  - chmod +x ./deployment/travis/scripts/install_clickhouse.sh
  - ./deployment/travis/scripts/install_clickhouse.sh
  - chmod +x ./deployment/travis/scripts/configure_clickhouse.sh
  - ./deployment/travis/scripts/configure_clickhouse.sh
  - cat /etc/clickhouse-server/config.yml
  - cp .env.travis .env
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - php artisan key:generate
  - php artisan migrate

before_install:
  - chmod +x ./deployment/travis/scripts/install_postgresql_11.sh
  - ./deployment/travis/scripts/install_postgresql_11.sh
  - chmod +x ./deployment/travis/scripts/configure_postgresql.sh
  - ./deployment/travis/scripts/configure_postgresql.sh

script:
  - phpunit

services:
  - postgresql
  - rabbitmq

addons:
  postgresql: "11.3"

branches:
  only:
    - master
    - develop

notifications:
  email: false
