version: "3.3"

services:

  nginx:
    build:
      context: .
      dockerfile: deployment/local/docker/nginx/Dockerfile
    ports:
      - "${DOCKER_NGINX_PORT}:80"
    links:
      - php-fpm
    volumes:
      - ./:/var/www
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: .
      dockerfile: deployment/local/docker/php-fpm/Dockerfile
    volumes:
      - ./:/var/www
    links:
      - pgsql
      - clickhouse-client
      - rabbitmq
    depends_on:
      - pgsql
      - clickhouse-client
      - rabbitmq
    container_name: logs_php_fpm

  pgsql:
    build:
      context: .
      dockerfile: deployment/local/docker/pgsql/Dockerfile
    ports:
      - "${DOCKER_PGSQL_PORT}:5432"
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./persistent_data/pgsql:/var/lib/postgresql/data

  rabbitmq:
    build:
      context: .
      dockerfile: deployment/local/docker/rabbitmq/Dockerfile
    ports:
      - "${DOCKER_RABBITMQ_PORT}:5672"
    environment:
      - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_DEFAULT_VHOST}
    container_name: logs_rabbitmq

  clickhouse-server:
    build:
      context: .
      dockerfile: deployment/local/docker/clickhouse-server/Dockerfile
    ports:
      - "${DOCKER_CLICKHOUSE_SERVER_PORT}:8123"
    environment:
      - CLICKHOUSE_USER=${DB_CLICKHOUSE_USERNAME}
      - CLICKHOSUE_PASSWORD=${DB_CLICKHOUSE_PASSWORD}
    volumes:
      - ./persistent_data/clickhouse-server:/var/lib/clickhouse
    container_name: logs_clickhouse_server

  clickhouse-client:
    build:
      context: .
      dockerfile: deployment/local/docker/clickhouse-client/Dockerfile
    ports:
      - "${DOCKER_CLICKHOUSE_CLIENT_PORT}:9000"
    volumes:
      - ./persistent_data/clickhouse-client:/var/lib/clickhouse
    depends_on:
      - clickhouse-server
    links:
      - clickhouse-server
    container_name: logs_clickhouse_client

