version: "3.3"

services:

  nginx:
    build:
      context: .
      dockerfile: deployment/local/docker/nginx/Dockerfile
    ports:
      - "${DOCKER_NGINX_PORT}:80"
    links:
      - php-fpm
    volumes:
      - ./:/var/www
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: .
      dockerfile: deployment/local/docker/php-fpm/Dockerfile
    volumes:
      - ./:/var/www
    links:
      - mysql
    depends_on:
      - mysql
    container_name: logs_php_fpm

  mysql:
    build:
      context: .
      dockerfile: deployment/local/docker/mysql/Dockerfile
    ports:
      - "${DOCKER_MYSQL_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    volumes:
      - ./persistent_data/mysql:/var/lib/mysql

  mysql_testing:
    build:
      context: .
      dockerfile: deployment/local/docker/mysql_testing/Dockerfile
    ports:
      - "${DOCKER_MYSQL_TESTING_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD={DB_TESTING_PASSWORD}
      - MYSQL_DATABASE={DB_TESTING_DATABASE}
    volumes:
      - ./persistent_data/mysql_testing:/var/lib/mysql

